Global Function, Refresh Galleries and Albums, Code Cleanup and Other…
fooplugins/foogallery-migrate pull request #5
Opened 2023-01-11 12:04 UTC by Code-BeautifulWeb

@bradvin Please review the PR!

2023-01-11 19:22 UTC, bradvin requested changes

2023-01-11 19:22 UTC, bradvin commented on includes/objects/class-migratable.php
> +                    if($this->children_name() == 'galleries' && $this->get_total_images() == $this->get_total_migrated_images()) {
Why is this check needed?

2023-01-11 19:22 UTC, bradvin commented on includes/plugins/class-photo.php
> +                    $migrated_object = foogallery_migrate_migrator_instance()->has_object_been_migrated( $unique_identifier );
this code is redundant, as this logic now exists in get_album function

2023-01-11 19:22 UTC, bradvin commented on includes/objects/class-plugin.php
> +        function get_image( $data = array() ) {
add PHP comments to the function

2023-01-11 19:22 UTC, bradvin commented on includes/objects/class-plugin.php
> +        function get_album( $data = array() ) {
add PHP comments to the function

2023-01-11 19:22 UTC, bradvin commented on includes/objects/class-plugin.php
> +        function get_gallery( $data = array() ) {
add php comments to function

2023-01-12 08:48 UTC, Code-BeautifulWeb commented on includes/objects/class-migratable.php
> +                    if($this->children_name() == 'galleries' && $this->get_total_images() == $this->get_total_migrated_images()) {
This is for the Album. If you migrate all Galleries and then migrate the album then the UI stops there so I added this condition.

2023-01-12 08:56 UTC, Code-BeautifulWeb commented on includes/plugins/class-photo.php
> +                    $migrated_object = foogallery_migrate_migrator_instance()->has_object_been_migrated( $unique_identifier );
Sorry I forgot to remove this... Fixed in latest commit.

2023-01-12 08:56 UTC, Code-BeautifulWeb commented on includes/objects/class-plugin.php
> +        function get_image( $data = array() ) {
Updated in latest commit

2023-01-12 08:56 UTC, Code-BeautifulWeb commented on includes/objects/class-plugin.php
> +        function get_album( $data = array() ) {
Updated in latest commit

2023-01-12 08:56 UTC, Code-BeautifulWeb commented on includes/objects/class-plugin.php
> +        function get_gallery( $data = array() ) {
Updated in latest commit

2023-01-14 14:15 UTC, merged